In [1]:
import matplotlib
matplotlib.rcParams['pdf.fonttype'] = 42
matplotlib.rcParams['ps.fonttype'] = 42

import ptitprince as pt
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os

In [122]:
plot_info = []

for root, sub_dir, files in os.walk("../utils"):
    for file in files:
        if file.endswith(".csv"):
            try:
                src_file = file
                dim = int(file[3])
                obj = int(file[9])
                tree = file[16:].strip(".csv")
                df = pd.read_csv(src_file,index_col=0).fillna(0)
                df["dimension"] = dim
                df["n_objectives"] = obj
                df["tree"] = tree
                plot_info.append(df)
            except Exception as e:
                pass

In [123]:
new_df = pd.concat(plot_info)

In [124]:
new_df

,solver,exp_index,root,node_1,node_2,node_3,node_4,node_5,dimension,n_objectives,tree
0,NSGAII,36033,100,0,0,0,0,0,4,3,breadth
1,NSGAII,36034,100,0,0,0,0,0,4,3,breadth
2,NSGAII,36035,100,0,0,0,0,0,4,3,breadth
3,NSGAII,36036,100,0,0,0,0,0,4,3,breadth
4,NSGAII,36037,100,0,0,0,0,0,4,3,breadth
...,...,...,...,...,...,...,...,...,...,...,...
843,IBEA,20160,81,8,5,5,1,0,3,4,depth
844,IBEA,20161,74,10,10,1,5,0,3,4,depth
845,IBEA,20162,89,6,2,1,2,0,3,4,depth
846,IBEA,20163,73,11,10,2,4,0,3,4,depth
847,IBEA,20164,67,22,5,3,3,0,3,4,depth

In [127]:
solver = "GDE3"
dim_n_obj_combs = [(2,3),(2,4),(2,5),(3,3),(3,4),(3,5),(4,3),(4,4),(4,5),(5,3),(5,4),(5,5)]
tree = "breadth"
active_comb = dim_n_obj_combs[-1]

dimension = active_comb[0]
n_objectives = active_comb[1]
filtered_df = new_df[(new_df["solver"]==solver) & (new_df["dimension"]==dimension)&(new_df["tree"]==tree)&(new_df["n_objectives"]==n_objectives)]

In [128]:
filtered_df

,solver,exp_index,root,node_1,node_2,node_3,node_4,node_5,dimension,n_objectives,tree
300,GDE3,33630,100,0,0,0,0,0,5,5,breadth
301,GDE3,33631,100,0,0,0,0,0,5,5,breadth
302,GDE3,33632,100,0,0,0,0,0,5,5,breadth
303,GDE3,33633,100,0,0,0,0,0,5,5,breadth
304,GDE3,33634,100,0,0,0,0,0,5,5,breadth
...,...,...,...,...,...,...,...,...,...,...,...
595,GDE3,33925,100,0,0,0,0,0,5,5,breadth
596,GDE3,33926,100,0,0,0,0,0,5,5,breadth
597,GDE3,33927,100,0,0,0,0,0,5,5,breadth
598,GDE3,33928,100,0,0,0,0,0,5,5,breadth
599,GDE3,33929,100,0,0,0,0,0,5,5,breadth

In [129]:
filtered_df["root"].mean()

100.0

In [130]:
filtered_df["root"].std()

0.0

In [131]:
solvers = ["MOEAD","NSGAII","GDE3","IBEA"]
dimensions = [2,3,4,5]
n_objectives = [2,3,4,5]
tree = "depth"
df_info = []
for dimension in dimensions:
    for n_objective in n_objectives:
        for solver in solvers:
            filtered_df = new_df[(new_df["solver"]==solver) & (new_df["dimension"]==dimension)&(new_df["tree"]==tree)&(new_df["n_objectives"]==n_objective)]
            if not filtered_df.empty:
                df_info.append({
                    "solver":solver,
                    "dimX":dimension,
                    "dimZ":n_objective,
                    "root_mean":filtered_df["root"].mean(),
                    "root_std":filtered_df["root"].std(),
                    "node_1_mean":filtered_df["node_1"].mean(),
                    "node_1_std":filtered_df["node_1"].std(),
                    "node_2_mean":filtered_df["node_2"].mean(),
                    "node_2_std":filtered_df["node_2"].std(),
                    "node_3_mean":filtered_df["node_3"].mean(),
                    "node_3_std":filtered_df["node_3"].std(),
                    "node_4_mean":filtered_df["node_4"].mean(),
                    "node_4_std":filtered_df["node_4"].std(),
                })

In [132]:
stat_df = pd.DataFrame(df_info)

In [133]:
stat_df

,solver,dimX,dimZ,root_mean,root_std,node_1_mean,node_1_std,node_2_mean,node_2_std,node_3_mean,node_3_std,node_4_mean,node_4_std
0,NSGAII,2,3,98.857143,2.156235,1.071429,2.056532,0.066667,0.250040,0.004762,0.069007,0.000000,0.000000
1,GDE3,2,3,98.533333,1.279703,1.371429,1.262315,0.085714,0.297173,0.009524,0.097356,0.000000,0.000000
2,IBEA,2,3,75.595238,8.261456,13.866667,5.347390,6.295238,3.269180,2.004762,1.709802,2.238095,1.822369
3,NSGAII,2,4,96.804762,3.654319,3.033333,3.494881,0.147619,0.439790,0.014286,0.118950,0.000000,0.000000
4,GDE3,2,4,98.571429,1.296718,1.347619,1.274753,0.080952,0.306421,0.000000,0.000000,0.000000,0.000000
5,IBEA,2,4,74.204762,5.814598,14.466667,4.128479,6.466667,2.549291,2.333333,1.753556,2.528571,1.761264
6,NSGAII,2,5,98.504762,2.362481,1.357143,2.141205,0.128571,0.412302,0.009524,0.097356,0.000000,0.000000
7,GDE3,2,5,98.514286,1.387672,1.428571,1.357997,0.052381,0.223326,0.004762,0.069007,0.000000,0.000000
8,IBEA,2,5,80.300000,4.606060,9.342857,2.987465,5.276190,2.468927,2.742857,1.771808,2.338095,1.623681
9,NSGAII,3,3,99.943396,0.302601,0.056604,0.302601,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,GDE3,3,3,99.905660,0.308745,0.084906,0.295878,0.009434,0.096898,0.000000,0.000000,0.000000,0.000000
11,IBEA,3,3,77.500000,7.993777,12.707547,5.407502,5.330189,3.032905,2.075472,1.695817,2.386792,1.959644
12,NSGAII,3,4,99.622642,0.864824,0.372642,0.858637,0.004717,0.068680,0.000000,0.000000,0.000000,0.000000
13,GDE3,3,4,99.929245,0.257022,0.070755,0.257022,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,IBEA,3,4,77.386792,5.835129,12.353774,4.018009,5.136792,2.582325,2.089623,1.751502,3.033019,2.131649
15,NSGAII,3,5,99.896226,0.411430,0.099057,0.370217,0.004717,0.068680,0.000000,0.000000,0.000000,0.000000
16,GDE3,3,5,99.905660,0.308745,0.094340,0.308745,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
17,IBEA,3,5,84.721698,5.133562,7.250000,3.017916,3.547170,2.166667,2.599057,1.845861,1.882075,1.834441
18,NSGAII,4,3,99.995283,0.068680,0.004717,0.068680,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,GDE3,4,3,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,IBEA,4,3,79.419811,7.733609,11.995283,5.195238,4.523585,2.473444,1.698113,1.695658,2.363208,1.909111
21,NSGAII,4,4,99.962264,0.272761,0.037736,0.272761,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,GDE3,4,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23,IBEA,4,4,79.287736,4.972649,11.334906,3.685003,4.617925,2.320373,2.099057,1.540788,2.660377,1.931955
24,NSGAII,4,5,99.990566,0.096898,0.009434,0.096898,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25,GDE3,4,5,99.995283,0.068680,0.004717,0.068680,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
26,IBEA,4,5,88.391509,4.513542,5.773585,2.841077,2.990566,2.198644,2.367925,2.200067,0.476415,1.059558
27,NSGAII,5,3,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
28,GDE3,5,3,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
29,IBEA,5,3,80.231132,7.569481,11.443396,5.106599,4.155660,2.775881,1.712264,1.740850,2.457547,1.945487
30,NSGAII,5,4,99.995283,0.068680,0.004717,0.068680,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
31,GDE3,5,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
32,IBEA,5,4,80.311321,5.421326,10.849057,3.627939,4.283019,2.233967,2.009434,1.677819,2.547170,1.930705
33,NSGAII,5,5,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
34,GDE3,5,5,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
35,IBEA,5,5,91.556604,4.654061,4.646226,3.004315,3.042453,2.788448,0.740566,1.343284,0.014151,0.118393

In [134]:
solver_df = stat_df[stat_df["solver"]=="GDE3"]

In [135]:
solver_df

,solver,dimX,dimZ,root_mean,root_std,node_1_mean,node_1_std,node_2_mean,node_2_std,node_3_mean,node_3_std,node_4_mean,node_4_std
1,GDE3,2,3,98.533333,1.279703,1.371429,1.262315,0.085714,0.297173,0.009524,0.097356,0.0,0.0
4,GDE3,2,4,98.571429,1.296718,1.347619,1.274753,0.080952,0.306421,0.000000,0.000000,0.0,0.0
7,GDE3,2,5,98.514286,1.387672,1.428571,1.357997,0.052381,0.223326,0.004762,0.069007,0.0,0.0
10,GDE3,3,3,99.905660,0.308745,0.084906,0.295878,0.009434,0.096898,0.000000,0.000000,0.0,0.0
13,GDE3,3,4,99.929245,0.257022,0.070755,0.257022,0.000000,0.000000,0.000000,0.000000,0.0,0.0
16,GDE3,3,5,99.905660,0.308745,0.094340,0.308745,0.000000,0.000000,0.000000,0.000000,0.0,0.0
19,GDE3,4,3,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
22,GDE3,4,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
25,GDE3,4,5,99.995283,0.068680,0.004717,0.068680,0.000000,0.000000,0.000000,0.000000,0.0,0.0
28,GDE3,5,3,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
31,GDE3,5,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
34,GDE3,5,5,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0

In [120]:
str_write = (f"$\operatorname{{dim}}X=3$ & Mean & X.XX & Y.YY &X.XX & Y.YY &X.XX & Y.YY &X.XX & Y.YY &X.XX & Y.YY \\\\ \n"
            f"$\operatorname{{dim}}Z=4$ & Std & X.XX & Y.YY &X.XX & Y.YY &X.XX & Y.YY &X.XX & Y.YY &X.XX & Y.YY \\\\ \hline")
print(str_write)

$\operatorname{dim}X=3$ & Mean & X.XX & Y.YY &X.XX & Y.YY &X.XX & Y.YY &X.XX & Y.YY &X.XX & Y.YY \\
$\operatorname{dim}Z=4$ & Std & X.XX & Y.YY &X.XX & Y.YY &X.XX & Y.YY &X.XX & Y.YY &X.XX & Y.YY \\ \hline

In [121]:
for dimension in dimensions:
    for n_objective in n_objectives:
        res_df = stat_df[(stat_df['dimX']==dimension)&(stat_df['dimZ']==n_objective)]
        res_df = res_df.round(2)
        if not res_df.empty:
            s1 = (res_df[res_df['solver']=='GDE3'].iloc[0])
            s2 = (res_df[res_df['solver']=='NSGAII'].iloc[0])
            str_write = (f"$\operatorname{{dim}}X={dimension}$ & Mean & {s1['root_mean']} & {s1['node_1_mean']} & {s1['node_2_mean']} & {s1['node_3_mean']} &{s1['node_4_mean']} "
                         f"& {s2['root_mean']} & {s2['node_1_mean']} & {s2['node_2_mean']} & {s2['node_3_mean']} &{s2['node_4_mean']} \\\\ \n"
            f"$\operatorname{{dim}}Z={n_objective}$ & Std & {s1['root_std']} & {s1['node_1_std']} & {s1['node_2_std']} & {s1['node_3_std']} &{s1['node_4_std']}  "
            f"& {s2['root_std']} & {s2['node_1_std']} & {s2['node_2_std']} & {s2['node_3_std']} &{s2['node_4_std']} \\\\ \hline")
            print(str_write)
            print("\n")

$\operatorname{dim}X=2$ & Mean & 98.53 & 1.37 & 0.09 & 0.01 &0.0 & 98.86 & 1.07 & 0.07 & 0.0 &0.0 \\
$\operatorname{dim}Z=3$ & Std & 1.28 & 1.26 & 0.3 & 0.1 &0.0  & 2.16 & 2.06 & 0.25 & 0.07 &0.0 \\ \hline


$\operatorname{dim}X=2$ & Mean & 98.57 & 1.35 & 0.08 & 0.0 &0.0 & 96.8 & 3.03 & 0.15 & 0.01 &0.0 \\
$\operatorname{dim}Z=4$ & Std & 1.3 & 1.27 & 0.31 & 0.0 &0.0  & 3.65 & 3.49 & 0.44 & 0.12 &0.0 \\ \hline


$\operatorname{dim}X=2$ & Mean & 98.51 & 1.43 & 0.05 & 0.0 &0.0 & 98.5 & 1.36 & 0.13 & 0.01 &0.0 \\
$\operatorname{dim}Z=5$ & Std & 1.39 & 1.36 & 0.22 & 0.07 &0.0  & 2.36 & 2.14 & 0.41 & 0.1 &0.0 \\ \hline


$\operatorname{dim}X=3$ & Mean & 99.91 & 0.08 & 0.01 & 0.0 &0.0 & 99.94 & 0.06 & 0.0 & 0.0 &0.0 \\
$\operatorname{dim}Z=3$ & Std & 0.31 & 0.3 & 0.1 & 0.0 &0.0  & 0.3 & 0.3 & 0.0 & 0.0 &0.0 \\ \hline


$\operatorname{dim}X=3$ & Mean & 99.93 & 0.07 & 0.0 & 0.0 &0.0 & 99.62 & 0.37 & 0.0 & 0.0 &0.0 \\
$\operatorname{dim}Z=4$ & Std & 0.26 & 0.26 & 0.0 & 0.0 &0.0  & 0.86 & 0.86 & 0.07 & 0.0 &0.0 \\ \hline


$\operatorname{dim}X=3$ & Mean & 99.91 & 0.09 & 0.0 & 0.0 &0.0 & 99.9 & 0.1 & 0.0 & 0.0 &0.0 \\
$\operatorname{dim}Z=5$ & Std & 0.31 & 0.31 & 0.0 & 0.0 &0.0  & 0.41 & 0.37 & 0.07 & 0.0 &0.0 \\ \hline


$\operatorname{dim}X=4$ & Mean & 100.0 & 0.0 & 0.0 & 0.0 &0.0 & 100.0 & 0.0 & 0.0 & 0.0 &0.0 \\
$\operatorname{dim}Z=3$ & Std & 0.0 & 0.0 & 0.0 & 0.0 &0.0  & 0.07 & 0.07 & 0.0 & 0.0 &0.0 \\ \hline


$\operatorname{dim}X=4$ & Mean & 100.0 & 0.0 & 0.0 & 0.0 &0.0 & 99.96 & 0.04 & 0.0 & 0.0 &0.0 \\
$\operatorname{dim}Z=4$ & Std & 0.0 & 0.0 & 0.0 & 0.0 &0.0  & 0.27 & 0.27 & 0.0 & 0.0 &0.0 \\ \hline


$\operatorname{dim}X=4$ & Mean & 100.0 & 0.0 & 0.0 & 0.0 &0.0 & 99.99 & 0.01 & 0.0 & 0.0 &0.0 \\
$\operatorname{dim}Z=5$ & Std & 0.07 & 0.07 & 0.0 & 0.0 &0.0  & 0.1 & 0.1 & 0.0 & 0.0 &0.0 \\ \hline


$\operatorname{dim}X=5$ & Mean & 100.0 & 0.0 & 0.0 & 0.0 &0.0 & 100.0 & 0.0 & 0.0 & 0.0 &0.0 \\
$\operatorname{dim}Z=3$ & Std & 0.0 & 0.0 & 0.0 & 0.0 &0.0  & 0.0 & 0.0 & 0.0 & 0.0 &0.0 \\ \hline


$\operatorname{dim}X=5$ & Mean & 100.0 & 0.0 & 0.0 & 0.0 &0.0 & 100.0 & 0.0 & 0.0 & 0.0 &0.0 \\
$\operatorname{dim}Z=4$ & Std & 0.0 & 0.0 & 0.0 & 0.0 &0.0  & 0.07 & 0.07 & 0.0 & 0.0 &0.0 \\ \hline


$\operatorname{dim}X=5$ & Mean & 100.0 & 0.0 & 0.0 & 0.0 &0.0 & 100.0 & 0.0 & 0.0 & 0.0 &0.0 \\
$\operatorname{dim}Z=5$ & Std & 0.0 & 0.0 & 0.0 & 0.0 &0.0  & 0.0 & 0.0 & 0.0 & 0.0 &0.0 \\ \hline